### ISSUE TITLE
Order due time Slack notification

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#149]
## Issue Summary:
In parallel with SMS notification for order meal best to have also other channel of notification. One of most usable for us is Slack.
## Issue Details:
Required to create another job application which will send notification by Slack channel, about order details.
## Todo:
- [ ] Create Go lang application for send order details message to Slack channel, at order due time.

## Acceptance Criteria:
- Slack channel user shall receive order details notification, when order due time is over.

**Comment by ca7alindev** [comment]
@web7evgheni, please check PR
