### ISSUE TITLE
Build Process Failure on Linux/amd64: Error Encountered During Compilation

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#22]
### What happened?
Github Actions which building application for linux/amd64, encountering error,
take a look this action: https://github.com/kndpio/kndp/actions/runs/7891267345/job/21535225376

### How can we reproduce it?

https://github.com/kndpio/kndp/actions/runs/7891267345/job/21535225376

### What environment did it happen in?
KNDP version: 0.0.1

**Comment by ca7alindev** [comment]
@web7evgheni action encountered this error because is trying to push the binaries into release that triggered it, but the release doesn't exist yet.

**Comment by web7evgheni** [comment]
@ca7alindev Please make release, if not exists, in this action.
