### ISSUE TITLE
Command for moving environment to another context

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#25]
### What problem are you facing?
Currently is impossible to move all installed resources from one KNDP Environment to another.

### How could KNDP help solve your problem?
Would be goo to have `kndp env move --dest <env_name>` command which will move all resources and configurations created or applied by KNDP CLI to destination environment (practically Kubernetes cluster context)

**Comment by web7evgheni** [comment]
@ca7alindev Any news? Do you have idea how to mark resources?

**Comment by ca7alindev** [comment]
@web7evgheni Is possible to mark resources when user create them from huh form, with annotation and label, but i am not sure if we should let users to chose the values for labels and annotations, or maybe it should be a default static value provided in source code
