### ISSUE TITLE
On move simple Environment to GKE error appears

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#63]
### What happened?
While executing `kndp env move` where destination is GKE cluster, next error appears:
"ERRO the server could not find the requested resource"

### How can we reproduce it?
1. Create local env.
2. Apply configuration.
3. Get access to GKE cluster.
4. Execute move to from local to GKE.

### What environment did it happen in?
KNDP version:  develop

**Comment by ca7alindev** [comment]
@web7evgheni, consider closing this issue in favor of  https://github.com/kndpio/kndp/issues/62, where this issue is solved by ensuring configuration health before applying the resources.
